apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eddytor.server.name" . }}
  labels:
    {{- include "eddytor.labels" . | nindent 4 }}
    app: {{ include "eddytor.server.name" . }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eddytor.engine.name" . }}
  labels:
    {{- include "eddytor.labels" . | nindent 4 }}
    app: {{ include "eddytor.engine.name" . }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
